import React, { useRef, useEffect, useState } from 'react';
import { ExternalLink, Maximize2, Minimize2 } from 'lucide-react';
import { Modal } from '../common';

export interface CollectionDashboardModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const CollectionDashboardModal: React.FC<CollectionDashboardModalProps> = ({ isOpen, onClose }) => {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // Send Gemini API key to iframe once it loads
  useEffect(() => {
    if (!isOpen) return;
    const key = process.env.GEMINI_API_KEY;
    if (!key) return;

    const sendKey = () => {
      iframeRef.current?.contentWindow?.postMessage(
        { type: 'gemini-key', key },
        '*'
      );
    };

    const iframe = iframeRef.current;
    if (iframe) {
      iframe.addEventListener('load', sendKey);
      return () => iframe.removeEventListener('load', sendKey);
    }
  }, [isOpen]);

  const toggleFullscreen = () => {
    const el = containerRef.current;
    if (!el) return;

    if (!document.fullscreenElement) {
      el.requestFullscreen().then(() => setIsFullscreen(true)).catch(() => {});
    } else {
      document.exitFullscreen().then(() => setIsFullscreen(false)).catch(() => {});
    }
  };

  useEffect(() => {
    const handler = () => setIsFullscreen(!!document.fullscreenElement);
    document.addEventListener('fullscreenchange', handler);
    return () => document.removeEventListener('fullscreenchange', handler);
  }, []);

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Collection Dashboard — Historic Flour Mills"
      maxWidth="max-w-7xl"
    >
      <div className="text-left space-y-4" dir="ltr">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <p className="text-sm text-slate-600 leading-relaxed max-w-2xl">
              Interactive 11-tab collection dashboard generated by the Read-Collection (MA-RC) workflow.
              38 historic flour mills in Israel — overview, map, values matrix, knowledge graph with AI query, and more.
            </p>
            <div className="flex flex-wrap gap-2 mt-2">
              {['Overview', 'Map', 'Values', 'Arguments', 'Gaps', 'Clusters', 'AI Query'].map(tab => (
                <span key={tab} className="px-2 py-0.5 bg-slate-100 text-slate-600 rounded text-[10px] font-bold uppercase tracking-wider">
                  {tab}
                </span>
              ))}
            </div>
          </div>
          <div className="flex gap-2 shrink-0">
            <button
              onClick={toggleFullscreen}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 text-slate-600 rounded-lg text-xs font-bold hover:bg-slate-200 transition-colors"
              title={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
            >
              {isFullscreen ? <Minimize2 size={12} /> : <Maximize2 size={12} />}
              {isFullscreen ? 'Exit' : 'Fullscreen'}
            </button>
            <a
              href="/collection-dashboard-demo.html"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-50 text-indigo-600 rounded-lg text-xs font-bold hover:bg-indigo-100 transition-colors"
            >
              <ExternalLink size={12} />
              Open in new tab
            </a>
          </div>
        </div>

        {/* Desktop: iframe */}
        <div ref={containerRef} className="hidden sm:block rounded-xl overflow-hidden border border-slate-200 shadow-sm bg-white">
          <iframe
            ref={iframeRef}
            src="./collection-dashboard-demo.html"
            className="w-full border-0"
            style={{ height: isFullscreen ? '100vh' : '75vh', minHeight: '500px' }}
            title="Collection Dashboard — Historic Flour Mills of Israel"
          />
        </div>

        {/* Mobile: link only */}
        <div className="sm:hidden p-4 bg-slate-50 rounded-xl border border-slate-200">
          <p className="text-sm text-slate-600 text-center">
            The interactive dashboard is best experienced on desktop.
          </p>
          <a
            href="/collection-dashboard-demo.html"
            target="_blank"
            rel="noopener noreferrer"
            className="mt-3 flex items-center justify-center gap-1.5 px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-bold hover:bg-indigo-700 transition-colors"
          >
            <ExternalLink size={14} />
            Open Dashboard
          </a>
        </div>
      </div>
    </Modal>
  );
};

export default CollectionDashboardModal;
